### ISSUE TITLE
global music component

### ISSUE THREAD

**Issue by javenschuetz** [TheWizardsCode/Character#10]
supports reactive music blending #

**Comment by SorraTheOrc** [comment]
There is an existing directive in the InkManager to play music. This component needs to integrate with that. See https://github.com/TheWizardsCode/Character/blob/e3f4cb7feeeb017f229ec6bb618359a712c4de1b/Assets/WizardsCode/Character/Scripts/Ink/InkManager.cs#L454

**Comment by javenschuetz** [comment]
I'll have the existing logic invoke the doodad I'm building to get the parallel tracks going
