### ISSUE TITLE
InkManager -- wait state assumes only one wait at a time

### ISSUE THREAD

**Issue by javenschuetz** [TheWizardsCode/Character#32]
If ever we had to wait for 2 things to happen instead of just one, we would resume too early with the current setup. We could fix this by making a simple list of 'wait' objects, and we know we are not waiting any more if the list is empty.

Low priority and not causing any issues atm

**Comment by SorraTheOrc** [comment]
Simply add a second wait instruction after the first. The engine will wait for the first condition then test the second. If it has already passed then it will move on, if not it will wait.
